server:
  port: 8083
  servlet:
    context-path: /NewsDatabase

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NewsDatabase
    username: root
    password: "@Luvanthanh24072005"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
