server:
  port: 8080
  servlet:
    context-path: /MyPhoneStore

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyPhoneStore
    username: root
    password: "@Luvanthanh24072005"

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


